spring:
  application:
    name: CampusRecruitmentSystem
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':               # 匹配所有请求
            allowedOrigins: "*"  #跨域处理 允许所有的域
            allowedMethods:      # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true # 开启文件上传
      file-size-threshold: 2KB # 文件写入磁盘的阈值
      max-file-size: 100MB
      max-request-size: 215MB # 最大请求值大小

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.43.158.100:3306/hyh_project?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

file:
  prefix: F:\files\

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


---
spring:
  profiles: dev
server:
  port: 9090
eureka:
  client:
    service-url:
       defaultZone: http://admin:admin@121.43.158.100:8761/eureka/

---
spring:
  profiles: test
server:
  port: 9091
eureka:
  client:
    service-url:
       defaultZone: http://admin:admin@121.43.158.100:8761/eureka/

---
spring:
  profiles: pro
server:
  port: 9092
eureka:
  client:
    service-url:
       defaultZone: http://admin:admin@121.43.158.100:8761/eureka/
